apiVersion: apps/v1
kind: Deployment
metadata:
  name: timezones-service
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: timezones-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  template:
    metadata:
      labels:
        pod: timezones-service
    spec:
      containers:
        - name: timezone-service-container
          image: docker.io/reversearrow/timezones:latest
